# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argo-cd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/sambo2021/helm-charts.git
#     path: charts/argocd-test/argo-cd/
#     targetRevision: master
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       selfHeal: true