apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-istiod
spec:
  project: default
  source:
    repoURL: https://github.com/sambo2021/helm-charts.git
    path: charts/istio-istiod-test/istiod/
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true